version: '3.1'

services:
  postgres:
    image: postgres
    container_name: 'java-postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: 13047804kl
      POSTGRES_USER: postgres
      POSTGRES_DB: coda2

  adminer:
    image: adminer
    restart: always
    ports:
    - 8081:8080

  app:
    build: ./
    container_name: 'java-app'
    ports:
     - 8080:8080

