spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/coda2
    username: postgres
    password: 13047804kl

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  application:
    name: liquibase demo


#logging:
#  level:
#    org.springframework.web: ERROR
#    library.authentication.controller: DEBUG
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
#    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
#    #name: C:/IT projects/coda.log
#  file:
#    name: C:/IT projects/Repository Library_Test/Library_Test/logging.log