spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coda2
    username: postgres
    password: 13047804kl

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  application:
    name: liquibase demo
